#!/bin/sh
# Instruction:
#   A simple build script of xavs2 for iOS platform.
# Author:
#   Shen Wei <aosept@gmail.com>
#
# reference: http://blog.csdn.net/u010963658/article/details/51404710
#            https://github.com/yixia/x264.git
# PIE:       http://stackoverflow.com/questions/30612067/only-position-independent-executables-pie-are-supported
#            https://github.com/danielkop/android-ffmpeg/commit/616a099151fb6be05b559adc4c9ed95afacd92c2

# ------------------------------------------------------
# ARCH configurations: (arm/arm64), sdk-verision (19， 21)
#     only 21 and later version supports arm64

xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/block_info.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/cg_scan.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/common.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/common_arm.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/cpu.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/cudata.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/filter_alf.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/filter_deblock.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/filter_sao.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/frame.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/intra.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/mc.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/pixel.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/primitives.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/quant.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/threadpool.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/transform.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/common/win32thread.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/aec.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/aec_ctx.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/aec_fastrdo.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/aec_rdo.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/aec_vrdo.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/alf.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/encoder.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/encoder_report.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/header.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/md_inter.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/md_intra.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/me.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c -o parameters.o  ../../../xavs2/source/encoder/parameters.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c -o  pre_encode.o  ../../../xavs2/source/encoder/pre_encode.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/presets.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/ratecontrol.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/rdo.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/rdoq.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/rps.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c  -o sao.o  ../../../xavs2/source/encoder/sao.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/slice.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/tdrdo.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/wquant.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/wrapper.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c -o xavs2.o  ../../../xavs2/source/encoder/xavs2.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/xavs2_api.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/xlist.c
xcrun -sdk iphoneos clang   -Wno-uninitialized -Wshadow -O3 -ffast-math -m64  -Wall -I. -I../../..//xavs2/source -mdynamic-no-pic -arch arm64 -std=gnu99 -D_GNU_SOURCE -fomit-frame-pointer -fno-tree-vectorize -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -I. -I../../..//xavs2/source -I../../..//xavs2/source/common -I../../..//xavs2/source/common/x86 -I../../..//xavs2/source/common/vec -I../../..//xavs2/source/encoder -I../../..//xavs2/source/test -c   ../../../xavs2/source/encoder/yuv_writer.c

ar rc libxavs2.a  block_info.o common.o cpu.o cudata.o cg_scan.o frame.o intra.o mc.o pixel.o quant.o threadpool.o transform.o win32thread.o primitives.o filter_alf.o filter_deblock.o filter_sao.o aec_ctx.o aec.o aec_rdo.o aec_fastrdo.o aec_vrdo.o alf.o encoder.o encoder_report.o header.o me.o ratecontrol.o sao.o wquant.o md_intra.o md_inter.o presets.o pre_encode.o rdo.o rdoq.o rps.o slice.o tdrdo.o yuv_writer.o wrapper.o xavs2.o xavs2_api.o xlist.o parameters.o
